<script>
export default {
  mounted() {
    if (!localStorage.getItem("brands")) {
      localStorage.setItem("brands", JSON.stringify(this.brands));
    }
  },
  data() {
    return {
      brands: [
        {
          name: "adidas",
          video: {
            title: "IMPOSSIBLE IS NOTHING",
          },
          products: [
            {
              title: "NMD R1",
              subtitle: "Disney Pixar - Toy Story",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2099000,
              stock: 10,
            },
            {
              title: "PW HU HOLI NMD MC",
              subtitle: "Pink Glow",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5499000,
              stock: 10,
            },
            {
              title: "PW HU NMD NERD",
              subtitle: "N.E.R.D",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "10.5", "11.5", "12"],
              colours: ["#FFFFF"],
              price: 36099000,
              stock: 10,
            },
            {
              title: "PW HU NMD NERD",
              subtitle: "ComplexCon Exclusive 2018",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "7.5", "9.5"],
              colours: ["#FFFFF"],
              price: 21199000,
              stock: 10,
            },
            {
              title: "PHARRELL WILLIAMS SOLAR HU NMD",
              subtitle: "Solar Pack - M1L3L3",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 6099000,
              stock: 10,
            },
          ],
        },
        {
          name: "bape",
          video: {
            title: "BAPE® x COACH",
          },
          products: [
            {
              title: "BABY MILO CREWNECK",
              subtitle: "BAPE x Kid Cudi - Grey",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 3199000,
              stock: 10,
            },
            {
              title: "BABY MILO CREWNECK",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 3199000,
              stock: 10,
            },
            {
              title: "PULLOVER HOODIE",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 4599000,
              stock: 10,
            },
            {
              title: "BABY MILO PULLOVER HOODIE",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 4799000,
              stock: 10,
            },
            {
              title: "SWEAT CARDIGAN",
              subtitle: "BAPE x Kid Cudi",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 6199000,
              stock: 10,
            },
          ],
        },
        {
          name: "nike",
          video: {
            title: "Best Day Ever",
          },
          products: [
            {
              title: "AIR FORCE 1 LOW '07",
              subtitle: "White on White",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 1799000,
              stock: 10,
            },
            {
              title: "AIR FORCE 1 LOW",
              subtitle: "Supreme - Mini Box Logo White",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2799000,
              stock: 10,
            },
            {
              title: "AIR MAX 1",
              subtitle: "Blueprint",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3799000,
              stock: 10,
            },
            {
              title: "AIR FORCE 1 '07 WB",
              subtitle: "Flax",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2499000,
              stock: 10,
            },
            {
              title: "AIR MAX 90 RETRO",
              subtitle: "Bacon 2021",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2699000,
              stock: 10,
            },
          ],
        },
        {
          name: "jordan",
          video: {
            title: "Why Not?",
          },
          products: [
            {
              title: "AIR JORDAN 1 HIGH 85",
              subtitle: "Georgetown",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 6999000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 HIGH OG",
              subtitle: "Brotherhood",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3499000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 MID SE",
              subtitle: "Coconut Milk",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3399000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 HIGH OG",
              subtitle: "Dark Marina Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3699000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 RETRO HIGH OG",
              subtitle: "Bred Patent",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5599000,
              stock: 10,
            },
          ],
        },
        {
          name: "off-white",
          video: {
            title: '"Out of Office"',
          },
          products: [
            {
              title: "Gradient Arr",
              subtitle: "Pkt Skat L/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 7499000,
              stock: 10,
            },
            {
              title: "Monalisa",
              subtitle: "Slim S/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 6599000,
              stock: 10,
            },
            {
              title: "Caravaggio Painting",
              subtitle: "L/S T-Shirt",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M"],
              colours: ["#FFFFF"],
              price: 6499000,
              stock: 10,
            },
            {
              title: "Single Arrow",
              subtitle: "Slim S/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S"],
              colours: ["#FFFFF"],
              price: 5599000,
              stock: 10,
            },
            {
              title: "Diag Outline Skate",
              subtitle: "L/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS"],
              colours: ["#FFFFF"],
              price: 6499000,
              stock: 10,
            },
          ],
        },
        {
          name: "stussy",
          video: {
            title: "Persona",
          },
          products: [
            {
              title: "titel",
              subtitle: "subtitel",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8"],
              colours: ["#FFFFF"],
              price: 100000,
              stock: 10,
            },
          ],
        },
        {
          name: "yeezy",
          video: {
            title: "Dream. Create. Conquer.",
          },
          products: [
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Zebra - 2018/2019 Release",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5299000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Bone",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 4899000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2 REFLECTIVE",
              subtitle: "Beluga",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5699000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Dazzling Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5199000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 700",
              subtitle: "Wave Runner",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5999000,
              stock: 10,
            },
          ],
        },
      ],
    };
  },
};
</script>
