<script>
export default {
  mounted() {
    if (!localStorage.getItem("brands")) {
      localStorage.setItem("brands", JSON.stringify(this.brands));
    }
    if (!localStorage.getItem("types")) {
      localStorage.setItem("types", JSON.stringify(this.types));
    }
  },
  data() {
    return {
      types: ["shoes", "hat"],
      brands: [
        {
          name: "adidas",
          video: {
            title: "IMPOSSIBLE IS NOTHING",
          },
          products: [
            {
              title: "HU NMD",
              subtitle: "Multicolor",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/z/gz1664_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/z/gz1664_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/z/gz1664_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3600000,
              stock: 10,
            },
            {
              title: "NMD R1",
              subtitle: "Boba Fett Spectoo",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6791_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6791_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6791_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2300000,
              stock: 10,
            },
            {
              title: "4DFWD X PARLEY",
              subtitle: "Multicolor",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6313_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6313_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6313_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 4000000,
              stock: 10,
            },
            {
              title: "Ultraboost 22",
              subtitle: "Red",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/x/gx5462_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx5462_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6313_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3300000,
              stock: 10,
            },
            {
              title: "BOSSK NMD R1",
              subtitle: "Spectoo",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6792_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx6792_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/x/gx692_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["7.5", "8", "8.5", "9", "9.5"],
              colours: ["#FFFFF"],
              price: 2300000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 5.0",
              subtitle: "DNA",
              img: [
                "https://www.adidas.co.id/media/catalog/product/g/y/gy8614_flt_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/y/gy8614_mp_ecom.jpg",
                "https://www.adidas.co.id/media/catalog/product/g/y/gy8614_tpp_ecom.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["7", "7.5", "8", "8.5", "9"],
              colours: ["#FFFFF"],
              price: 3200000,
              stock: 10,
            },
            {
              title: "NMD R1",
              subtitle: "Disney Pixar - Toy Story",
              img: "https://assets.solesense.com/en/images/products/500/adidas-disney-pixar-x-nmd-r1-v1-toy-story-white-gx0996_1.jpg",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2099000,
              stock: 10,
            },
            {
              title: "PW HU HOLI NMD MC",
              subtitle: "Pink Glow",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5499000,
              stock: 10,
            },
            {
              title: "PW HU NMD NERD",
              subtitle: "N.E.R.D",
              img: "https://mysportsshoe.com/wp-content/uploads/2018/09/805002_011-600x600.jpg",
              type: "shoes",
              gender: "men",
              size: ["8", "10.5", "11.5", "12"],
              colours: ["#FFFFF"],
              price: 36099000,
              stock: 10,
            },
            {
              title: "PW HU NMD NERD",
              subtitle: "ComplexCon Exclusive 2018",
              img: "https://mysportsshoe.com/wp-content/uploads/2018/11/805368_02.jpg",
              type: "shoes",
              gender: "men",
              size: ["7", "7.5", "9.5"],
              colours: ["#FFFFF"],
              price: 21199000,
              stock: 10,
            },
            {
              title: "PHARRELL WILLIAMS SOLAR HU NMD",
              subtitle: "Solar Pack - M1L3L3",
              img: "https://assets.solesense.com/en/images/products/500/adidas-pharrell-nmd-hu-trail-solar-pack-bb9528_1.jpg",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 6099000,
              stock: 10,
            },
            {
              title: "ULTRA 4D 5.0",
              subtitle: "Black Carbon",
              img: "https://assets.solesense.com/en/images/products/500/adidas-ultra-4d-5-0-carbon-g58160_1.jpg",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3942000,
              stock: 10,
            },
            {
              title: "Adidas",
              subtitle: "Ultraboost",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2555000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 1.0 DNA CLOUD WHITE",
              subtitle: "Legacy Indigo",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3343400,
              stock: 10,
            },
            {
              title: "ULTRABOOST 4.0",
              subtitle: "Ivy Park",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2482000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 4.0 DNA",
              subtitle: "Football Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2993000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 20",
              subtitle: "What The Solar",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 1971000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 21",
              subtitle: "Tokyo",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3942000,
              stock: 10,
            },
            {
              title: "ULTRABOOST 22",
              subtitle: "Stella McCartney",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 4365400,
              stock: 10,
            },
            {
              title: "ULTRABOOST CNY",
              subtitle: "CNY",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3504000,
              stock: 10,
            },
            {
              title: "Adidas",
              subtitle: "Ultraboost M",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2993000,
              stock: 10,
            },
            {
              title: "Ultraboost LTD",
              subtitle: "Multi-Color Toe Navy",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2263000,
              stock: 10,
            },
            {
              title: "Ultraboost",
              subtitle: "Night's Watch",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2847000,
              stock: 10,
            },
            {
              title: "Ultraboost",
              subtitle: "Reflective",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2847000,
              stock: 10,
            },
            {
              title: "Ultraboost S&L",
              subtitle: "W",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2117000,
              stock: 10,
            },
            {
              title: "Ultraboost",
              subtitle: "Uncaged",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2175400,
              stock: 10,
            },
          ],
        },
        {
          name: "bape",
          video: {
            title: "BAPE® x COACH",
          },
          products: [
            {
              title: "BABY MILO CREWNECK",
              subtitle: "BAPE x Kid Cudi - Grey",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 3199000,
              stock: 10,
            },
            {
              title: "BABY MILO CREWNECK",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 3199000,
              stock: 10,
            },
            {
              title: "PULLOVER HOODIE",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 4599000,
              stock: 10,
            },
            {
              title: "BABY MILO PULLOVER HOODIE",
              subtitle: "BAPE x Kid Cudi - Black",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"],
              price: 4799000,
              stock: 10,
            },
            {
              title: "SWEAT CARDIGAN",
              subtitle: "BAPE x Kid Cudi",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 6199000,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Ape Head Crystal Stone Mesh Cap",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180020IBKX/0ZXCPM180020IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 2847000,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Baby Milo Patchwork Tee",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXTEW10020XIBKX/0ZXTEW10020XIBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "t-shirt",
              gender: "women",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1430800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Baseball Jacket",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXJKM14002XHGRX/0ZXJKM14002XHGRX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "jacket",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 6482400,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "BAPE Classic Logo Reversible Bucket Hat",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXHTM181001IMLX/0ZXHTM181001IMLX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 2146200,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "BAPE Girl Tee",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXTEM109007INYX/0ZXTEM109007INYX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1649800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "BAPE STA #3 M2 Sneakers",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXSHM191009IBKZ/0ZXSHM191009IBKZ-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "shoes",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4511400,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "BAPE Text Stripe Jersey Top",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXJKM113013HBDX/0ZXJKM113013HBDX-pdp-1.JPG?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "jackets",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4234000,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "College Panel Cap",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180006IBGX/0ZXCPM180006IBGX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1854200,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Color Camo C By Bathing Ape Tee",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXTEM110019IBKM/0ZXTEM110019IBKM-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1430800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Color Camo C Side Shark Tee",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXTEM110021IBKM/0ZXTEM110021IBKM-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "t-shirt",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1649800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Road STA #2 M1",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXTEM110021IBKM/0ZXTEM110021IBKM-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "shoes",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4934800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Road STA #2 M1",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXSHM191007IIVK/0ZXSHM191007IIVK-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "shoes",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4934800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "Tie-Dye Bucket Hat",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXHTM181016INYX/0ZXHTM181016INYX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 1941800,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "X Ghostbusters Camo Baby Milo Double Bape Sta",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXSHM191944GPPP/0ZXSHM191944GPPP-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4905600,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "X Heron Preston Mix 1st Camo Duck Tracker Jacket M2 ",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXJKM141902IPPX/0ZXJKM141902IPPX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "cap",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4905600,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "X Heron Preston Mix 1st Camo Duck Tracker Jacket M2 ",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXJKM141902IPPX/0ZXJKM141902IPPX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "jackets",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 4905600,
              stock: 10,
            },
            {
              title: "A BATHING APE",
              subtitle: "X Heron Preston Relaxed Tee",
              img: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXJKM141902IPPX/0ZXJKM141902IPPX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
              type: "jackets",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"],
              price: 2993000,
              stock: 10,
            },
          ],
        },
        {
          name: "nike",
          video: {
            title: "Best Day Ever",
          },
          products: [
            {
              title: "Airmax 97",
              subtitle: "By You",
              img: [
                "https://www.nike.com/id/u/custom-nike-air-force-97-by-you-10001072/2361189699",
                "https://www.nike.com/id/u/custom-nike-air-force-97-by-you-10001072/2361189699",
                "https://www.nike.com/id/u/custom-nike-air-force-97-by-you-10001072/2361189699",
              ],
              type: "shoes",
              gender: "men",
              size: [
                "6",
                "6.5",
                "7",
                "7.5",
                "8",
                "8.5",
                "9",
                "9.5",
                "10",
                "10.5",
                "11",
                "11.5",
                "12",
                "12.5",
                "13",
                "14",
                "15",
              ],
              colours: ["#FFFFF"],
              price: 2989000,
              stock: 10,
            },
            {
              title: "AIR FORCE 1 LOW '07",
              subtitle: "White on White",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 1799000,
              stock: 10,
            },
            {
              title: "AIR FORCE 1 LOW",
              subtitle: "Supreme - Mini Box Logo White",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2799000,
              stock: 10,
            },
            {
              title: "AIR MAX 1",
              subtitle: "Blueprint",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3799000,
              stock: 10,
            },
            {
              title: "AIR FORCE 1 '07 WB",
              subtitle: "Flax",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2499000,
              stock: 10,
            },
            {
              title: "AIR MAX 90 RETRO",
              subtitle: "Bacon 2021",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 2699000,
              stock: 10,
            },
          ],
        },
        {
          name: "jordan",
          video: {
            title: "Why Not?",
          },
          products: [
            //======================== jordan 1 ============================
            {
              title: "AIR JORDAN 1 HIGH 85",
              subtitle: "Georgetown",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 6999000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 HIGH OG",
              subtitle: "Brotherhood",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3499000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 MID SE",
              subtitle: "Coconut Milk",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3399000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 HIGH OG",
              subtitle: "Dark Marina Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3699000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 RETRO HIGH OG",
              subtitle: "Bred Patent",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5599000,
              stock: 10,
            },
            {
              title: "WMNS AIR JORDAN 1 MID SE",
              subtitle: "Berry Pink",
              img: "",
              type: "shoes",
              gender: "women",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3099000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 RETRO HIGH OG",
              subtitle: "Bordeaux",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 3299000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 MID",
              subtitle: "Light Smoke Grey 2.0",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["9.5", "13"],
              colours: ["#FFFFF"],
              price: 4599000,
              stock: 10,
            },
            {
              title: "JORDAN 1 MID PS",
              subtitle: "Black / White/ Racer Blue",
              img: "",
              type: "shoes",
              gender: "kids",
              size: ["11C", "11.5C", "12C", "12.5C", "13"],
              colours: ["#FFFFF"],
              price: 2299000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 1 RETRO HIGH OG",
              subtitle: "Obsidian/University Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 9599000,
              stock: 10,
            },
            //======================== jordan 4 ============================
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Fire Red 2020",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 8299000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Bred 2019 Release",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 13099000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO NRG",
              subtitle: "Levi's",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8.5", "12.5"],
              colours: ["#FFFFF"],
              price: 24599000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Lightning 2021",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5499000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO SP WMNS",
              subtitle: "Off-White - Sail",
              img: "",
              type: "shoes",
              gender: "women",
              size: ["8", "8.5", "9.5", "11", "11.5"],
              colours: ["#FFFFF"],
              price: 20199000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Fire Red 2020",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 7999000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Lightning 2021",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5499000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO SP WMNS",
              subtitle: "Off-White - Sail",
              img: "",
              type: "shoes",
              gender: "women",
              size: ["8", "8.5", "9.5", "11", "11.5"],
              colours: ["#FFFFF"],
              price: 20199000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: `"KAWS"`,
              img: [
                "https://img.stadiumgoods.com/12/95/91/37/12959137_34437196_2048.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8.5", "9.5", "10.5", "12"],
              colours: ["#FFFFF"],
              price: 111499000,
              stock: 10,
            },
            {
              title: "AIR JORDAN 4 RETRO",
              subtitle: "Kaws - Black",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8.5", "9.5", "10", "10.5", "11"],
              colours: ["#00000"],
              price: 92099000,
              stock: 10,
            },
          ],
        },
        {
          name: "off-white",
          video: {
            title: '"Out of Office"',
          },
          products: [
            {
              title: "Gradient Arr",
              subtitle: "Pkt Skat L/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 7499000,
              stock: 10,
            },
            {
              title: "Monalisa",
              subtitle: "Slim S/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 6599000,
              stock: 10,
            },
            {
              title: "Caravaggio Painting",
              subtitle: "L/S T-Shirt",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M"],
              colours: ["#FFFFF"],
              price: 6499000,
              stock: 10,
            },
            {
              title: "Single Arrow",
              subtitle: "Slim S/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S"],
              colours: ["#FFFFF"],
              price: 5599000,
              stock: 10,
            },
            {
              title: "Diag Outline Skate",
              subtitle: "L/S Tee",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS"],
              colours: ["#FFFFF"],
              price: 6499000,
              stock: 10,
            },
            {
              title: "Monalisa Arrow",
              subtitle: "Hoodie-Black",
              img: [
                "https://cdn-images.farfetch-contents.com/16/04/66/08/16046608_34158851_2048.jpg?c=3",
              ],
              type: "hoodie",
              gender: "men",
              size: ["XXS", "XS"],
              colours: ["#00000"],
              price: 10499000,
              stock: 10,
            },
            {
              title: "Monalisa Arrow",
              subtitle: "Hoodie-White",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["XXS", "XS", "S"],
              colours: ["#FFFFF"],
              price: 10499000,
              stock: 10,
            },
            {
              title: "Monalisa Over",
              subtitle: "Crewneck-Black",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#00000"],
              price: 10499000,
              stock: 10,
            },
            {
              title: "Monalisa Over",
              subtitle: "Hoodie-Black",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#00000"],
              price: 10999000,
              stock: 10,
            },
            {
              title: "Monalisa Over",
              subtitle: "Hoodie-White",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"],
              price: 10999000,
              stock: 10,
            },
            {
              title: "High Top Vulcanized Leather",
              subtitle: "White sneakers",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "8", "9", "10", "11"],
              colours: ["#FFFFF"], //cream white yellow
              price: 11099000,
              stock: 10,
            },
            {
              title: "New Mid Top Sponge Sneaker",
              subtitle: "'OUT OF OFFICE' sneakers",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "8", "9", "10", "11"],
              colours: ["#FFFFF"],
              price: 11099000,
              stock: 10,
            },
            {
              title: "5.0 Sneakers",
              subtitle: "Low top 5.0 sneakers in white",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "8", "9", "10", "11"],
              colours: ["#FFFFF"],
              price: 8199000,
              stock: 10,
            },
            {
              title: "Low Vulcanized Canvas",
              subtitle: "white/multicolour leather",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "8", "9", "10", "11", "12"],
              colours: ["#FFFFF"],
              price: 5199000,
              stock: 10,
            },
            {
              title: "3.0 Off Court Supreme Suede",
              subtitle: "white and blue with Off-White™ logo",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["7", "8", "9", "10", "11", "12"],
              colours: ["#FFFFF"],
              price: 13399000,
              stock: 10,
            },
            {
              title: "Off Stamp Cropped Hoodie",
              subtitle: "in black with Off™ logo in white",
              img: "",
              type: "hoodie",
              gender: "women",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#00000"],
              price: 10799000,
              stock: 10,
            },
            {
              title: "Off Stamp Cropped Crewneck",
              subtitle: "in black with Off logo",
              img: "",
              type: "t-shirt",
              gender: "women",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#00000"],
              price: 10299000,
              stock: 10,
            },
            {
              title: "Diag Regular Crewneck",
              subtitle: "in beige with Off-White™ logo embroidered",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
              colours: ["#FFFFF"], //beige
              price: 11699000,
              stock: 10,
            },
            {
              title: "Monogram Allover Trackpant",
              subtitle: "in black with white logo printed",
              img: "",
              type: "pants",
              gender: "men",
              size: ["XS", "M"],
              colours: ["#FFFFF/#00000"],
              price: 14599000,
              stock: 10,
            },
            {
              title: "Caravaggio Painting Sweatpants",
              subtitle: "in black featuring Caravaggio",
              img: "",
              type: "pants",
              gender: "men",
              size: ["XXS", "XS", "S", "M", "L", "XL"],
              colours: ["#00000"],
              price: 8599000,
              stock: 10,
            },
          ],
        },
        {
          name: "stussy",
          video: {
            title: "Persona",
          },
          products: [
            {
              title: "FLORAL DYE WORK JACKET",
              subtitle:
                "Sturdy cotton canvas work jacket in allover flower dye print",
              img: "",
              type: "jacket",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#FFFFF"], //brown
              price: 3599000,
              stock: 10,
            },
            {
              title: "STOCK LOGO POCKET T-SHIRT",
              subtitle: "Chest pocket with embroidered stock logo",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["L"],
              colours: ["#00000"],
              price: 1299000,
              stock: 10,
            },
            {
              title: "PIGMENT DYED INSIDE-OUT T-SHIRT",
              subtitle: "Complete inside-out design with exposed seams",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XL"],
              colours: ["#FFFFF"], //Lavender
              price: 1399000,
              stock: 10,
            },
            {
              title: "FLOWER MOCK NECK LS CREW",
              subtitle: "Ribbed flower mockneck with Chest pocket",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["XL"],
              colours: ["#00000"],
              price: 1799000,
              stock: 10,
            },
            {
              title: "SWIRL APPLIQUÉ CREWNECK SWEATER",
              subtitle:
                "S' Swirl appliqué at chest Dropped shoulder Ribbed neckline, cuffs, and hem",
              img: "",
              type: "sweater",
              gender: "men",
              size: ["S", "M", "L"],
              colours: ["#FFFFF"], //Ash Heather
              price: 2399000,
              stock: 10,
            },
            {
              title: "STOCK LOGO HOOD",
              subtitle:
                "Drawstring hood Embroidered stock logo at center Ribbed hem, cuffs",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#00000"],
              price: 2599000,
              stock: 10,
            },
            {
              title: "FLORAL HOODIE",
              subtitle:
                "Allover floral print Drawstring hood Ribbed hem, cuffs",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["M", "L"],
              colours: ["#FFFFF"],
              price: 2799000,
              stock: 10,
            },
            {
              title: "DENIM CHORE JACKET",
              subtitle:
                "Button closure Embroidered logo at chest Total four front pockets",
              img: "",
              type: "jacket",
              gender: "men",
              size: ["L"],
              colours: ["#FFFFF"], //Blue
              price: 3399000,
              stock: 10,
            },
            {
              title: "ZIP-UP WORK SHIRT",
              subtitle:
                "Crisp poly blend exterior, Point collar, Zip closure, Two chest pocket, Logo patch at left pocket",
              img: "",
              type: "shirt",
              gender: "men",
              size: ["M"],
              colours: ["#00000"],
              price: 2649000,
              stock: 10,
            },
            {
              title: "FLAMES HOODIE",
              subtitle: "Screenprinted Flame logo at center with Pouch pocket",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["S", "L", "XL"],
              colours: ["#00000"], //Ash Heather
              price: 2399000,
              stock: 10,
            },
            {
              title: "SWIRL HOODIE",
              subtitle: "Long sleeve",
              img: "",
              type: "hoodie",
              gender: "men",
              size: ["M", "L"],
              colours: ["#FFFFF"], //green
              price: 2459000,
              stock: 10,
            },
            {
              title: "DICE PATTERN SHIRT",
              subtitle: "Allover dice pattern",
              img: "",
              type: "shirt",
              gender: "men",
              size: ["XL"],
              colours: ["#00000"],
              price: 2899000,
              stock: 10,
            },
            {
              title: "VERTICAL STRIPED KNIT CREW",
              subtitle: "Soft knitted crewneck sweater",
              img: "",
              type: "sweater",
              gender: "men",
              size: ["L", "XL"],
              colours: ["#FFFFF"], //green / red
              price: 2999000,
              stock: 10,
            },
            {
              title: "BRUSHED BEACH PANTS",
              subtitle: "Brushed cotton twill exterior",
              img: "",
              type: "pants",
              gender: "men",
              size: ["M", "L"],
              colours: ["#00000"],
              price: 2299000,
              stock: 10,
            },
            {
              title: "STOCK LOGO PANTS",
              subtitle: "Cotton fleece sweatpants",
              img: "",
              type: "pants",
              gender: "men",
              size: ["S", "M", "L", "XL"],
              colours: ["#00000"],
              price: 2399000,
              stock: 10,
            },
            {
              title: "NYCO CONVERTIBLE PANTS",
              subtitle: "with removable bottom hem",
              img: "",
              type: "pants",
              gender: "men",
              size: ["L", "XL"],
              colours: ["#00000"],
              price: 3199000,
              stock: 10,
            },
            {
              title: "NYLON RIPSTOP SURPLUS CARGO",
              subtitle: "with Adjustable waistband",
              img: "",
              type: "pants",
              gender: "men",
              size: ["30", "32", "34"],
              colours: ["#00000"],
              price: 2659000,
              stock: 10,
            },
            {
              title: "BRYAN PANTS",
              subtitle: "Elasticated waist with hidden drawcord",
              img: "",
              type: "pants",
              gender: "men",
              size: ["XL"],
              colours: ["#00000"],
              price: 2899000,
              stock: 10,
            },
            {
              title: "CORDUROY RELAXED PANT",
              subtitle: "Cotton corduroy constuction",
              img: "",
              type: "pants",
              gender: "men",
              size: ["M", "L", "XL"],
              colours: ["#00000"],
              price: 3549000,
              stock: 10,
            },
            {
              title: "ACID FLOWERS T-SHIRT",
              subtitle: "Short sleeve",
              img: "",
              type: "t-shirt",
              gender: "men",
              size: ["S"],
              colours: ["#00000"], //yellow green
              price: 1149000,
              stock: 10,
            },
          ],
        },
        {
          name: "yeezy",
          video: {
            title: "Dream. Create. Conquer.",
          },
          products: [
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Zebra - 2018/2019 Release",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5299000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Bone",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 4899000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2 REFLECTIVE",
              subtitle: "Beluga",
              img: [
                "https://img.stadiumgoods.com/17/70/19/91/17701991_37101727_2048.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5699000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Dazzling Blue",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5199000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 700",
              subtitle: "Wave Runner",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 5999000,
              stock: 10,
            },
            //====================Belum==================
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "MX Rock",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#00000"],
              price: 5459000,
              stock: 10,
            },
            {
              title: "AIR YEEZY 2 NRG",
              subtitle: "Solar Red",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["9.5", "10"],
              colours: ["#00000"],
              price: 263799000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 700 V2",
              subtitle: "Cream",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"], //cream
              price: 5769000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Desert Sage",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 8549000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2 REFLECTIVE",
              subtitle: "Citrin",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 12999000,
              stock: 10,
            },
            {
              title: "YEEZY 750 BOOST",
              subtitle: "grey",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["10"],
              colours: ["#FFFFF"],
              price: 48399000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Yeshaya",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 8599000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Beluga",
              img: [
                "https://img.stadiumgoods.com/11/70/76/53/11707653_34678121_2048.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 23249000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 INFANT",
              subtitle: "Pirate Black",
              img: "",
              type: "shoes",
              gender: "kids",
              size: ["5K", "6K", "8K", "9K"],
              colours: ["#FFFFF"],
              price: 16129000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Blue Tint",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#FFFFF"],
              price: 6299000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Mono Cinder",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8.5", "9.5", "10.5", "11"],
              colours: ["#FFFFF"],
              price: 6399000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Bred",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["8", "8.5", "9", "9.5", "10"],
              colours: ["#00000"],
              price: 8349000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V2",
              subtitle: "Green",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["9", "10.5", "11"],
              colours: ["#FFFFF"],
              price: 30799000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 350 V1",
              subtitle: "Pirate Black",
              img: [
                "https://img.stadiumgoods.com/12/96/02/76/12960276_34671715_2048.jpg",
              ],
              type: "shoes",
              gender: "men",
              size: ["8", "9", "11", "13", "14"],
              colours: ["#FFFFF"],
              price: 61549000,
              stock: 10,
            },
            {
              title: "YEEZY BOOST 750",
              subtitle: "Grey Gum",
              img: "",
              type: "shoes",
              gender: "men",
              size: ["6", "7", "7.5"],
              colours: ["#FFFFF"],
              price: 80549000,
              stock: 10,
            },
          ],
        },
      ],
    };
  },
};
</script>
